### ISSUE TITLE
Space engineers 1.087 with SE .527 slight problems :)

### ISSUE THREAD

**Issue by xxam** [SEServerExtender/SEServerExtender#69] opened 2015-06-18 21:02 UTC
I guess some stuff got moved again.

Logs showing: 

2015-06-18 22:59:11.4038|Info|EssentialsPlugin.Utility.Players.<ProcessServerLogsForLogins>b__e|Completed checking logs in 0,013s: 335 (0) steamIds
2015-06-18 22:59:11.8798|Warn|EssentialsPlugin.Essentials+<>c__DisplayClass3.<PluginProcessing>b__2|Handler Problems: 400 - System.MissingMethodException: Method not found: 'VRage.Utils.MyStringId VRage.ObjectBuilders.MyObjectBuilder_Base.get_SubtypeId()'.
   at SEModAPIInternal.API.Entity.BaseObject..ctor(MyObjectBuilder_Base baseEntity)
   at SEModAPIInternal.API.Entity.BaseEntity..ctor(MyObjectBuilder_EntityBase baseEntity)
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGridEntity..ctor(FileInfo prefabFile)
   at EssentialsPlugin.ProcessHandlers.ProcessCommunication.AddGlobalRelay()
   at EssentialsPlugin.ProcessHandlers.ProcessCommunication.Handle()
   at EssentialsPlugin.Essentials.<>c__DisplayClass3.<PluginProcessing>b__2()

**Comment by wweiland** [comment] 2015-06-18 21:14
Confirmed.  users sitting at waiting for server and logs scroll infinite.  Thank you again!

**Comment by dodexahedron** [comment] 2015-06-19 03:08
It never ends. :)
I'll fix it as soon as I get home.
Thanks

-----Original Message-----

**Comment by devu** [comment] 2015-06-19 08:09
It's a pain to see some fundamental things changing every Thursday but I've got impression this thing related to typeId and subtypeId was marked as obsolete in some places after last update. At least that helped to avoid me some issues.

Right now the Entity list is unusable.

**Comment by xxam** [comment] 2015-06-19 09:14
the entity-tab issue could be essentials related, i dont know if that is an error from the extender :)

**Comment by dodexahedron** [comment] 2015-06-19 13:20
It's just a type change in the game.
It's fixed in the upcoming release.

**Comment by devu** [comment] 2015-06-19 13:20
Well, crashes even when Essential is disabled. It looks like is trying to
get IDs and subIDs of entities for the list.

Log is flooded with this:

2015-06-19 14:12:51.7768|Error|System.Reflection.TargetInvocationException:
Exce
ption has been thrown by the target of an invocation. --->
System.MissingMethodE
xception: Method not found: 'VRage.Utils.MyStringId
VRage.ObjectBuilders.MyObjec
tBuilder_Base.get_SubtypeId()'.
   at SEModAPIInternal.API.Entity.BaseObject..ctor(MyObjectBuilder_Base
baseEnti
ty, Object backingObject)
   at
SEModAPIInternal.API.Entity.BaseEntity..ctor(MyObjectBuilder_EntityBase ba
seEntity, Object backingObject)
   at
SEModAPIInternal.API.Entity.Sector.SectorObject.CharacterEntity..ctor(MyOb
jectBuilder_Character definition, Object backingObject)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[]
arguments,
 Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags
invokeAttr, B
inder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr,
Binder bin
der, Object[] args, CultureInfo culture, Object[] activationAttributes,
StackCra
wlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr,
Binde
r binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at SEModAPIInternal.API.Entity.SectorObjectManager.LoadDynamic()

It will stop as soon as you  leave Entities tab.

I had version of my own plugin relying on SectorObjectManager and it's
broken as well.
Lucky I decided a while ago to use Sanbox Methods and it's all fine.

However accessing directly IMySlimBlock
block.FatBlock.GetObjectBuilderCubeBlock().BuildPercent = 0.5f; will no
longer work from yesterday :(.
Trying to remove block from grid will give you Exception as well.

So I am stack either way.

**Comment by dodexahedron** [comment] 2015-06-19 13:38
Fixed in 530, which was released a few seconds ago.

**Closed as completed by dodexahedron** 2015-06-19 13:38 UTC
