### ISSUE TITLE
auto clean deleting all entities

### ISSUE THREAD

**Issue by fo0** [SEServerExtender/SEServerExtender#9] opened 2015-03-26 09:08 UTC
If you setup auto clean, for example to a specific time, 08:44, then its always deleting EVERY entity, it doesnt care the command like "nopower".

**Comment by CJClaude** [comment] 2015-03-26 15:59
Confirmed this happened for me this morning as well.  Fortunately had a backup from 90 minutes prior to the autoclean.   I had two cleanups run:

1)  noownership to purge the explorer ships
2)  inactive 22 ignorenologin

I've purged the 2nd from the mod to help identify which is causing the problem.

For what its worth, both commands appear to work fine if done manually:

/admin delete grids noownership (except that it blows away CommRelayGlobal)
/admin delete inactive 22 ignorenologin

I've added an extra backup a few minutes before the autoclean just in case this is a repeatable problem.  That said, this is my first full day using this version of Extender/Extension.

**Comment by dodexahedron** [comment] 2015-03-27 05:50
Closing this as a duplicate of https://github.com/SEServerExtender/EssentialsPlugin/issues/2

**Closed as completed by dodexahedron** 2015-03-27 05:50 UTC
