### ISSUE TITLE
New Error 

### ISSUE THREAD

**Issue by Lordicon** [SEServerExtender/SEServerExtender#13] opened 2015-03-30 07:36 UTC
On Server load I am getting this error in yellow text, I believe it has something to do with the essentials not sure why I posted this in the extender section. This is latest version v1.75.6.336-alpha. Also clean up does not seem to be working and the waypoints and MOTD are not displaying in game.

2015-03-30 02:32:00.6010|Error|System.Reflection.TargetInvocationException: Exce
ption has been thrown by the target of an invocation. ---> System.TypeLoadExcept
ion: Could not load type 'NLog.Fluent.Log' from assembly 'NLog, Version=3.2.0.0,
 Culture=neutral, PublicKeyToken=5120e14c03d0593c'.
   at EssentialsPlugin.Utility.Players.Load()
   at EssentialsPlugin.ProcessHandlers.ProcessLoginTracking..ctor()
   at EssentialsPlugin.Essentials.DoInit(String path)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments,
 Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Objec
t[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invoke
Attr, Binder binder, Object[] parameters, CultureInfo culture)
   at SEModAPIExtensions.API.PluginManager.InitPlugin(Guid key)

**Comment by CJClaude** [comment] 2015-03-30 14:02
Also seeing something similar:  http://puu.sh/gVaXa/b4e243a4c0.png

**Comment by Lordicon** [comment] 2015-03-31 04:18
I believe it has something to do with setting "Player Login Tracking" to "true", I cleared all the files started fresh and did not get this error at server start up but when I tried to set this setting to true I got this popup error in the extender.

Could not load type 'NLog.Fluent.Log' from assembly 'NLog, Version=3.2.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c'.

**Comment by Lordicon** [comment] 2015-03-31 04:24
This happens on player joining server

2015-03-30 23:20:28.3265|Error|System.Reflection.TargetInvocationException: Exce
ption has been thrown by the target of an invocation. ---> System.TypeLoadExcept
ion: Could not load type 'NLog.Fluent.Log' from assembly 'NLog, Version=3.2.0.0,
 Culture=neutral, PublicKeyToken=5120e14c03d0593c'.
   at EssentialsPlugin.Utility.Players.Load()
   at EssentialsPlugin.ProcessHandlers.ProcessLoginTracking.OnPlayerJoined(UInt6
4 remoteUserId)
   at EssentialsPlugin.Essentials.OnPlayerJoined(UInt64 remoteUserId)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments,
 Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Objec
t[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invoke
Attr, Binder binder, Object[] parameters, CultureInfo culture)
   at SEModAPIExtensions.API.PluginManager.DoUpdate(Object args)

**Comment by dodexahedron** [comment] 2015-03-31 05:09
This is a duplicate of https://github.com/SEServerExtender/EssentialsPlugin/issues/9
Closing this in favor of that bug.

**Closed as completed by dodexahedron** 2015-03-31 05:09 UTC
