### ISSUE TITLE
|Info|SEModAPIExtensions.API.Server.RunServer|Server has stopped running

### ISSUE THREAD

**Issue by Embolex1** [SEServerExtender/SEServerExtender#18] opened 2015-04-16 02:26 UTC
SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper..ctor|Finished loading SandboxGameAssemblyWrapper
2015-04-14 22:18:22.0876|Info|SEModAPIExtensions.API.BasicUnitTestManager.RunBaseReflectionUnitTests|All main types passed reflection unit tests!
2015-04-14 22:18:22.1517|Info|SEModAPIExtensions.API.BasicUnitTestManager.RunEntityReflectionUnitTests|All entity types passed reflection unit tests!
2015-04-14 22:18:22.2548|Info|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|All block types passed reflection unit tests!
2015-04-14 22:18:22.2548|Info|SEModAPIExtensions.API.Server..ctor|Finished creating server!
2015-04-14 22:18:22.2688|Info|SEModAPIInternal.API.Server.ServerAssemblyWrapper.get_Instance|Finished loading ServerAssemblyWrapper
2015-04-14 22:18:22.2688|Info|SEModAPIExtensions.API.PluginManager..ctor|Finished loading PluginManager
2015-04-14 22:18:22.2688|Info|SEModAPIInternal.API.Common.FactionsManager.get_Instance|Finished loading FactionsManager
2015-04-14 22:18:22.2688|Info|SEModAPIInternal.API.Common.EntityEventManager.get_Instance|Finished loading EntityEventManager
2015-04-14 22:18:22.3058|Info|SEModAPIExtensions.API.ChatManager..ctor|Finished loading ChatManager
2015-04-14 22:18:22.3058|Info|SEModAPIExtensions.API.Server.ProcessCommandLineArgs|Auto-Start enabled
2015-04-14 22:18:22.3058|Info|SEModAPIExtensions.API.Server.ProcessCommandLineArgs|Common instance pre-selected: 'Survival PvP No Rules Stargates gereng'
2015-04-14 22:18:23.5770|Info|SEModAPIExtensions.API.SessionManager.UpdateSessionSettings|Loading Session Settings
2015-04-14 22:18:27.5246|Info|SEModAPIExtensions.API.SessionManager.UpdateSessionSettings|
Max Players: 24
2015-04-14 22:18:27.5246|Info|SEModAPIExtensions.API.SessionManager.UpdateSessionSettings|OnlineMode: PUBLIC
2015-04-14 22:18:27.5246|Info|SEModAPIExtensions.API.SessionManager.UpdateSessionSettings|GameMode: Survival
2015-04-14 22:18:27.5246|Info|SEModAPIExtensions.API.SessionManager.UpdateSessionSettings|Scenario: Asteroids
2015-04-14 22:18:27.5246|Info|SEModAPIExtensions.API.SessionManager.UpdateSessionSettings|World Size: 100000

2015-04-14 22:18:27.5246|Info|SEServerExtender.Program.Start|Opening up WCF service listener at http://localhost:5353/ServerService/Survival PvP No Rules Stargates gereng
2015-04-14 22:18:33.9115|Info|SEServerExtender.SEServerExtender.ChatViewRefresh|Finished loading PlayerManager
2015-04-14 22:18:33.9115|Info|SEServerExtender.SEServerExtender.ChatViewRefresh|Finished loading NetworkManager
2015-04-14 22:18:33.9115|Info|SEModAPIInternal.API.Common.PlayerMap.get_Instance|Finished loading PlayerMap
2015-04-14 22:20:46.5257|Info|SEModAPIExtensions.API.PluginManager.LoadPlugins|Loading plugins ...
2015-04-14 22:20:46.5257|Info|SEModAPIExtensions.API.PluginManager.LoadPlugins|Scanning: C:\ProgramData\SpaceEngineersDedicated\Survival PvP No Rules Stargates gereng\Mods
2015-04-14 22:20:46.5537|Info|SEModAPIExtensions.API.PluginManager.LoadPlugins|Finished loading plugins
2015-04-14 22:20:46.5537|Info|SEModAPIExtensions.API.PluginManager.Init|Initializing plugins ...
2015-04-14 22:20:46.5537|Info|SEModAPIExtensions.API.PluginManager.Init|Finished initializing plugins
2015-04-14 22:20:47.8620|Info|SEModAPIInternal.API.Common.FactionsManager.GetSubTypeEntity|Finished loading WorldManager
2015-04-14 22:23:28.1490|Info|SEModAPIInternal.API.Common.WorldManager+<>c__DisplayClass3.<AsynchronousSaveWorld>b__2|Asynchronous Save Setup Started: 228.2122ms
2015-04-14 22:23:30.6918|Info|SEModAPIInternal.API.Common.WorldManager+<>c__DisplayClass3.<AsynchronousSaveWorld>b__0|Asynchronous Save Completed: 2771.0281ms
2015-04-14 22:28:28.0074|Info|SEModAPIInternal.API.Common.WorldManager+<>c__DisplayClass3.<AsynchronousSaveWorld>b__2|Asynchronous Save Setup Started: 82.0765ms
2015-04-14 22:28:29.8221|Info|SEModAPIInternal.API.Common.WorldManager+<>c__DisplayClass3.<AsynchronousSaveWorld>b__0|Asynchronous Save Completed: 1896.7537ms
2015-04-14 22:33:28.0920|Info|SEModAPIInternal.API.Common.WorldManager+<>c__DisplayClass3.<AsynchronousSaveWorld>b__2|Asynchronous Save Setup Started: 165.1511ms
2015-04-14 22:33:30.8825|Info|SEModAPIInternal.API.Common.WorldManager+<>c__DisplayClass3.<AsynchronousSaveWorld>b__0|Asynchronous Save Completed: 2955.7305ms
2015-04-14 22:38:28.0922|Info|SEModAPIInternal.API.Common.WorldManager+<>c__DisplayClass3.<AsynchronousSaveWorld>b__2|Asynchronous Save Setup Started: 165.1533ms
2015-04-14 22:38:30.3183|Info|SEModAPIInternal.API.Common.WorldManager+<>c__DisplayClass3.<AsynchronousSaveWorld>b__0|Asynchronous Save Completed: 2391.2091ms
2015-04-14 22:43:28.0573|Info|SEModAPIInternal.API.Common.WorldManager+<>c__DisplayClass3.<AsynchronousSaveWorld>b__2|Asynchronous Save Setup Started: 117.1079ms
2015-04-14 22:43:29.4246|Info|SEModAPIInternal.API.Common.WorldManager+<>c__DisplayClass3.<AsynchronousSaveWorld>b__0|Asynchronous Save Completed: 1484.3722ms
2015-04-14 22:48:28.0416|Info|SEModAPIInternal.API.Common.WorldManager+<>c__DisplayClass3.<AsynchronousSaveWorld>b__2|Asynchronous Save Setup Started: 100.0922ms
2015-04-14 22:48:29.4429|Info|SEModAPIInternal.API.Common.WorldManager+<>c__DisplayClass3.<AsynchronousSaveWorld>b__0|Asynchronous Save Completed: 1501.3873ms
2015-04-14 22:53:28.0418|Info|SEModAPIInternal.API.Common.WorldManager+<>c__DisplayClass3.<AsynchronousSaveWorld>b__2|Asynchronous Save Setup Started: 99.0913ms
2015-04-14 22:53:29.5702|Info|SEModAPIInternal.API.Common.WorldManager+<>c__DisplayClass3.<AsynchronousSaveWorld>b__0|Asynchronous Save Completed: 1627.5042ms
2015-04-14 22:58:28.0481|Info|SEModAPIInternal.API.Common.WorldManager+<>c__DisplayClass3.<AsynchronousSaveWorld>b__2|Asynchronous Save Setup Started: 105.0971ms
2015-04-14 22:58:29.5785|Info|SEModAPIInternal.API.Common.WorldManager+<>c__DisplayClass3.<AsynchronousSaveWorld>b__0|Asynchronous Save Completed: 1635.5113ms
2015-04-14 23:03:28.0568|Info|SEModAPIInternal.API.Common.WorldManager+<>c__DisplayClass3.<AsynchronousSaveWorld>b__2|Asynchronous Save Setup Started: 101.0934ms
2015-04-14 23:03:30.0917|Info|SEModAPIInternal.API.Common.WorldManager+<>c__DisplayClass3.<AsynchronousSaveWorld>b__0|Asynchronous Save Completed: 2135.9744ms
2015-04-14 23:08:28.0489|Info|SEModAPIInternal.API.Common.WorldManager+<>c__DisplayClass3.<AsynchronousSaveWorld>b__2|Asynchronous Save Setup Started: 93.0857ms
2015-04-14 23:08:30.5882|Info|SEModAPIInternal.API.Common.WorldManager+<>c__DisplayClass3.<AsynchronousSaveWorld>b__0|Asynchronous Save Completed: 2632.4333ms
2015-04-14 23:13:28.0733|Info|SEModAPIInternal.API.Common.WorldManager+<>c__DisplayClass3.<AsynchronousSaveWorld>b__2|Asynchronous Save Setup Started: 118.1092ms
2015-04-14 23:13:29.4425|Info|SEModAPIInternal.API.Common.WorldManager+<>c__DisplayClass3.<AsynchronousSaveWorld>b__0|Asynchronous Save Completed: 1487.3747ms

.... ect .... and then ....

2015-04-15 20:23:31.1736|Info|SEModAPIInternal.API.Common.WorldManager+<>c__DisplayClass3.<AsynchronousSaveWorld>b__0|Asynchronous Save Completed: 2312.1376ms
2015-04-15 20:28:28.9922|Info|SEModAPIInternal.API.Common.WorldManager+<>c__DisplayClass3.<AsynchronousSaveWorld>b__2|Asynchronous Save Setup Started: 126.1175ms
2015-04-15 20:28:32.0683|Info|SEModAPIInternal.API.Common.WorldManager+<>c__DisplayClass3.<AsynchronousSaveWorld>b__0|Asynchronous Save Completed: 3202.1574ms
2015-04-15 20:32:37.7392|Info|SEModAPIExtensions.API.Server.RunServer|Server has stopped running

what log do u need to find the reason for this ?

**Comment by dodexahedron** [comment] 2015-04-25 06:00
If it's not in that log, it's not likely that Extender was the cause.
You can check the game's log in your world folder, but more than likely a mod  misbehaved or the game crashed.
Is there a windows application event log error at the time of the server crash?

**Comment by dodexahedron** [comment] 2015-04-27 04:31
Please update to version *.417 and let me know if you continue to see this crash.

**Comment by dodexahedron** [comment] 2015-04-29 16:11
This should be fixed, as it's fixed for other people who have reported the same issue to me.
Go ahead and re-open if this isn't working properly in version 419 or higher.

**Closed as completed by dodexahedron** 2015-04-29 16:11 UTC
Labels: bug
