### ISSUE TITLE
[Feature Request] Ability to differentiate running instance in logs

### ISSUE THREAD

**Issue by remygrandin** [SEServerExtender/SEServerExtender#7] opened 2015-03-24 14:32 UTC
Actually, the SEServerExtenderLog use the same file for every running instance.
It would be more practical to be able to differenciate instances, either by a separate logs (i don't remember if NLog allow run-time log file name changes) or by inserting the instance name in eache log line (something like 2015-03-24 15:23:18.4155|Info|InstanceName|LogContent)

**Comment by dodexahedron** [comment] 2015-03-25 03:56
Paths in the game are...insane.
I spent a couple of hours trying to find a good way to do this, when I was working on logging.
The problem is that SESE needs to log some things before the game launches, and then it needs to log some stuff after the game launches.
Unfortunately, before the game launches, there's no useful path, so there's no good way to accomplish this.

The previous version got around this by simply not writing it to a log file - it just wrote stuff to the console.
That's also not a good situation, because important things can be lost to the console.

I experimented with having separate lots for internal stuff and things that happen once the game launches, but this got unwieldy, and I also ran into path issues with game instances.

Maybe I just need to spend more time figuring out how pathing works in the game.
Any ideas?

**Comment by dodexahedron** [comment] 2015-03-25 03:58
My current recommendation to people is to simply have separate installs per instance.  The game isn't that big, and it can be faked with symlinks if you want to save hard drive space.

**Comment by remygrandin** [comment] 2015-03-25 07:14
Hmm,  I see. An idea could be this :
As you said, there would be a pre launch log which will be build,  but as soon as the game start to launch,  all log (including copy of all the pre launch ones)  would be written in an instance specific one.  That way, the "pre launch log"  would be useful only in case of crash.

**Comment by dodexahedron** [comment] 2015-03-27 05:57
How about this...
By default, the logs end up where SESE is currently writing them (wherever the config file says to put them).

But, if the user has specified an instance as a command line argument, logs get that instance name added to their file name (Intance1-ChatLog-2015-3-27.log for example).

That would be an extra requirement for multi-instance people, but it makes dealing with the game's HORRIBLE pathing a lot less of a problem.

**Comment by remygrandin** [comment] 2015-03-27 21:07
That sounds great, it will be a great steap for multiple instance servers ^^

**Comment by dodexahedron** [comment] 2015-04-03 20:17
This is the next work item I will be addressing.

**Comment by dodexahedron** [comment] 2015-04-05 06:20
This is released in version 1.76.11.367

**Closed as completed by dodexahedron** 2015-04-05 06:20 UTC
Labels: enhancement, discussion
