### ISSUE TITLE
extender .498 with space engineers 1.085 008

### ISSUE THREAD

**Issue by xxam** [SEServerExtender/SEServerExtender#56] opened 2015-06-04 20:01 UTC
2015-06-04 21:52:46.3916|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunBaseReflectionUnitTests|SandboxGameAssemblyWrapper reflection validation failed!

**Comment by xxam** [comment] 2015-06-04 20:05
its from server extenderlog

**Comment by dodexahedron** [comment] 2015-06-04 20:13
Closing this as duplicate of #55.

**Closed as completed by dodexahedron** 2015-06-04 20:13 UTC
Labels: duplicate
